name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [5.6, 7.0, 7.1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, php-xml, ext-dom, zip, pdo, sqlite
        coverage: none

    - name: Install Laravel Sample
      run: |
        git clone -b codeception-3.0 https://github.com/codeception/codeception-laravel5-sample.git framework-tests
        git --git-dir framework-tests/.git log -n 1
        composer update -d framework-tests --no-dev --prefer-dist --no-interaction
        cp framework-tests/.env.testing framework-tests/.env
        touch framework-tests/storage/testing.sqlite
        php framework-tests/artisan migrate --env=testing --database=sqlite_testing --force
        php framework-tests/artisan config:clear

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction --no-suggest

    - name: Run test suite
      run: |
        php ./vendor/bin/codecept build -c framework-tests
        php ./vendor/bin/codecept run functional -c framework-tests
